// Albion Online Item Database
// Organized by category with item IDs matching the Albion Online Data Project API

const ITEM_DATABASE = {
  // ─── RAW RESOURCES ───
  "Raw Resources": {
    "Hide": [
      "T2_HIDE", "T3_HIDE", "T4_HIDE", "T5_HIDE", "T6_HIDE", "T7_HIDE", "T8_HIDE"
    ],
    "Ore": [
      "T2_ORE", "T3_ORE", "T4_ORE", "T5_ORE", "T6_ORE", "T7_ORE", "T8_ORE"
    ],
    "Fiber": [
      "T2_FIBER", "T3_FIBER", "T4_FIBER", "T5_FIBER", "T6_FIBER", "T7_FIBER", "T8_FIBER"
    ],
    "Wood": [
      "T2_WOOD", "T3_WOOD", "T4_WOOD", "T5_WOOD", "T6_WOOD", "T7_WOOD", "T8_WOOD"
    ],
    "Rock": [
      "T2_ROCK", "T3_ROCK", "T4_ROCK", "T5_ROCK", "T6_ROCK", "T7_ROCK", "T8_ROCK"
    ]
  },

  // ─── REFINED MATERIALS ───
  "Refined Materials": {
    "Leather": [
      "T2_LEATHER", "T3_LEATHER", "T4_LEATHER", "T5_LEATHER", "T6_LEATHER", "T7_LEATHER", "T8_LEATHER"
    ],
    "Metal Bar": [
      "T2_METALBAR", "T3_METALBAR", "T4_METALBAR", "T5_METALBAR", "T6_METALBAR", "T7_METALBAR", "T8_METALBAR"
    ],
    "Cloth": [
      "T2_CLOTH", "T3_CLOTH", "T4_CLOTH", "T5_CLOTH", "T6_CLOTH", "T7_CLOTH", "T8_CLOTH"
    ],
    "Planks": [
      "T2_PLANKS", "T3_PLANKS", "T4_PLANKS", "T5_PLANKS", "T6_PLANKS", "T7_PLANKS", "T8_PLANKS"
    ],
    "Stoneblock": [
      "T2_STONEBLOCK", "T3_STONEBLOCK", "T4_STONEBLOCK", "T5_STONEBLOCK", "T6_STONEBLOCK", "T7_STONEBLOCK", "T8_STONEBLOCK"
    ]
  },

  // ─── FOOD & CONSUMABLES ───
  "Food & Potions": {
    "Cooked Food": [
      "T1_MEAL_SOUP", "T3_MEAL_SOUP", "T5_MEAL_SOUP", "T7_MEAL_SOUP",
      "T1_MEAL_SALAD", "T3_MEAL_SALAD", "T5_MEAL_SALAD", "T7_MEAL_SALAD",
      "T1_MEAL_SANDWICH", "T3_MEAL_SANDWICH", "T5_MEAL_SANDWICH", "T7_MEAL_SANDWICH",
      "T1_MEAL_PIE", "T3_MEAL_PIE", "T5_MEAL_PIE", "T7_MEAL_PIE",
      "T1_MEAL_OMELETTE", "T3_MEAL_OMELETTE", "T5_MEAL_OMELETTE", "T7_MEAL_OMELETTE",
      "T1_MEAL_STEW", "T3_MEAL_STEW", "T5_MEAL_STEW", "T7_MEAL_STEW"
    ],
    "Potions": [
      "T4_POTION_HEAL", "T5_POTION_HEAL", "T6_POTION_HEAL", "T7_POTION_HEAL", "T8_POTION_HEAL",
      "T4_POTION_ENERGY", "T5_POTION_ENERGY", "T6_POTION_ENERGY", "T7_POTION_ENERGY", "T8_POTION_ENERGY",
      "T1_POTION_COOLDOWN", "T3_POTION_COOLDOWN", "T5_POTION_COOLDOWN", "T7_POTION_COOLDOWN",
      "T4_POTION_RESISTANCE", "T5_POTION_RESISTANCE", "T6_POTION_RESISTANCE",
      "T2_POTION_MOB_TRACKING", "T4_POTION_MOB_TRACKING", "T6_POTION_MOB_TRACKING"
    ],
    "Crops": [
      "T1_CARROT", "T2_BEAN", "T3_WHEAT", "T4_TURNIP", "T5_CABBAGE",
      "T6_POTATO", "T7_CORN", "T8_PUMPKIN"
    ],
    "Raw Meat & Fish": [
      "T1_FISHSAUCE", "T2_FISHSAUCE", "T3_FISHSAUCE", "T4_FISHSAUCE",
      "T5_FISHSAUCE", "T6_FISHSAUCE", "T7_FISHSAUCE", "T8_FISHSAUCE"
    ]
  },

  // ─── BAGS & CAPES ───
  "Bags & Capes": {
    "Bags": [
      "T4_BAG", "T5_BAG", "T6_BAG", "T7_BAG", "T8_BAG",
      "T4_BAG@1", "T5_BAG@1", "T6_BAG@1", "T7_BAG@1", "T8_BAG@1",
      "T4_BAG@2", "T5_BAG@2", "T6_BAG@2", "T7_BAG@2", "T8_BAG@2",
      "T4_BAG@3", "T5_BAG@3", "T6_BAG@3", "T7_BAG@3", "T8_BAG@3"
    ],
    "Capes": [
      "T4_CAPEITEM_FW_BRIDGEWATCH", "T4_CAPEITEM_FW_FORTSTERLING",
      "T4_CAPEITEM_FW_LYMHURST", "T4_CAPEITEM_FW_MARTLOCK",
      "T4_CAPEITEM_FW_THETFORD", "T4_CAPEITEM_FW_CAERLEON",
      "T5_CAPEITEM_FW_BRIDGEWATCH", "T5_CAPEITEM_FW_FORTSTERLING",
      "T5_CAPEITEM_FW_LYMHURST", "T5_CAPEITEM_FW_MARTLOCK",
      "T5_CAPEITEM_FW_THETFORD", "T5_CAPEITEM_FW_CAERLEON",
      "T6_CAPEITEM_FW_BRIDGEWATCH", "T6_CAPEITEM_FW_FORTSTERLING",
      "T6_CAPEITEM_FW_LYMHURST", "T6_CAPEITEM_FW_MARTLOCK",
      "T6_CAPEITEM_FW_THETFORD", "T6_CAPEITEM_FW_CAERLEON",
      "T7_CAPEITEM_FW_BRIDGEWATCH", "T7_CAPEITEM_FW_FORTSTERLING",
      "T7_CAPEITEM_FW_LYMHURST", "T7_CAPEITEM_FW_MARTLOCK",
      "T7_CAPEITEM_FW_THETFORD", "T7_CAPEITEM_FW_CAERLEON",
      "T8_CAPEITEM_FW_BRIDGEWATCH", "T8_CAPEITEM_FW_FORTSTERLING",
      "T8_CAPEITEM_FW_LYMHURST", "T8_CAPEITEM_FW_MARTLOCK",
      "T8_CAPEITEM_FW_THETFORD", "T8_CAPEITEM_FW_CAERLEON"
    ]
  },

  // ─── MOUNTS ───
  "Mounts": {
    "Riding Horses": [
      "T3_MOUNT_HORSE", "T4_MOUNT_HORSE", "T5_MOUNT_HORSE", "T6_MOUNT_HORSE", "T7_MOUNT_HORSE", "T8_MOUNT_HORSE"
    ],
    "Armored Horses": [
      "T4_MOUNT_ARMORED_HORSE", "T5_MOUNT_ARMORED_HORSE", "T6_MOUNT_ARMORED_HORSE",
      "T7_MOUNT_ARMORED_HORSE", "T8_MOUNT_ARMORED_HORSE"
    ],
    "Oxen": [
      "T3_MOUNT_OX", "T4_MOUNT_OX", "T5_MOUNT_OX", "T6_MOUNT_OX", "T7_MOUNT_OX", "T8_MOUNT_OX"
    ]
  },

  // ─── WARRIOR WEAPONS ───
  "Warrior Weapons": {
    "Swords": [
      "T4_MAIN_SWORD", "T5_MAIN_SWORD", "T6_MAIN_SWORD", "T7_MAIN_SWORD", "T8_MAIN_SWORD",
      "T4_2H_CLAYMORE", "T5_2H_CLAYMORE", "T6_2H_CLAYMORE", "T7_2H_CLAYMORE", "T8_2H_CLAYMORE",
      "T4_2H_DUALSWORD", "T5_2H_DUALSWORD", "T6_2H_DUALSWORD", "T7_2H_DUALSWORD", "T8_2H_DUALSWORD",
      "T4_MAIN_SCIMITAR_MORGANA", "T5_MAIN_SCIMITAR_MORGANA", "T6_MAIN_SCIMITAR_MORGANA", "T7_MAIN_SCIMITAR_MORGANA", "T8_MAIN_SCIMITAR_MORGANA",
      "T4_2H_CLEAVER_HELL", "T5_2H_CLEAVER_HELL", "T6_2H_CLEAVER_HELL", "T7_2H_CLEAVER_HELL", "T8_2H_CLEAVER_HELL",
      "T4_2H_DUALSCIMITAR_UNDEAD", "T5_2H_DUALSCIMITAR_UNDEAD", "T6_2H_DUALSCIMITAR_UNDEAD", "T7_2H_DUALSCIMITAR_UNDEAD", "T8_2H_DUALSCIMITAR_UNDEAD"
    ],
    "Axes": [
      "T4_MAIN_AXE", "T5_MAIN_AXE", "T6_MAIN_AXE", "T7_MAIN_AXE", "T8_MAIN_AXE",
      "T4_2H_HALBERD", "T5_2H_HALBERD", "T6_2H_HALBERD", "T7_2H_HALBERD", "T8_2H_HALBERD",
      "T4_2H_HALBERD_MORGANA", "T5_2H_HALBERD_MORGANA", "T6_2H_HALBERD_MORGANA", "T7_2H_HALBERD_MORGANA", "T8_2H_HALBERD_MORGANA",
      "T4_2H_DUALAXE", "T5_2H_DUALAXE", "T6_2H_DUALAXE", "T7_2H_DUALAXE", "T8_2H_DUALAXE"
    ],
    "Maces": [
      "T4_MAIN_MACE", "T5_MAIN_MACE", "T6_MAIN_MACE", "T7_MAIN_MACE", "T8_MAIN_MACE",
      "T4_2H_MACE", "T5_2H_MACE", "T6_2H_MACE", "T7_2H_MACE", "T8_2H_MACE",
      "T4_2H_FLAIL", "T5_2H_FLAIL", "T6_2H_FLAIL", "T7_2H_FLAIL", "T8_2H_FLAIL",
      "T4_MAIN_ROCKMACE_KEEPER", "T5_MAIN_ROCKMACE_KEEPER", "T6_MAIN_ROCKMACE_KEEPER", "T7_MAIN_ROCKMACE_KEEPER", "T8_MAIN_ROCKMACE_KEEPER"
    ],
    "Hammers": [
      "T4_2H_POLEHAMMER", "T5_2H_POLEHAMMER", "T6_2H_POLEHAMMER", "T7_2H_POLEHAMMER", "T8_2H_POLEHAMMER",
      "T4_2H_HAMMER", "T5_2H_HAMMER", "T6_2H_HAMMER", "T7_2H_HAMMER", "T8_2H_HAMMER",
      "T4_2H_HAMMER_UNDEAD", "T5_2H_HAMMER_UNDEAD", "T6_2H_HAMMER_UNDEAD", "T7_2H_HAMMER_UNDEAD", "T8_2H_HAMMER_UNDEAD",
      "T4_2H_DUALHAMMER_HELL", "T5_2H_DUALHAMMER_HELL", "T6_2H_DUALHAMMER_HELL", "T7_2H_DUALHAMMER_HELL", "T8_2H_DUALHAMMER_HELL"
    ],
    "Crossbows": [
      "T4_2H_CROSSBOW", "T5_2H_CROSSBOW", "T6_2H_CROSSBOW", "T7_2H_CROSSBOW", "T8_2H_CROSSBOW",
      "T4_2H_CROSSBOWLARGE", "T5_2H_CROSSBOWLARGE", "T6_2H_CROSSBOWLARGE", "T7_2H_CROSSBOWLARGE", "T8_2H_CROSSBOWLARGE",
      "T4_MAIN_1HCROSSBOW", "T5_MAIN_1HCROSSBOW", "T6_MAIN_1HCROSSBOW", "T7_MAIN_1HCROSSBOW", "T8_MAIN_1HCROSSBOW"
    ],
    "Shields": [
      "T4_OFF_SHIELD", "T5_OFF_SHIELD", "T6_OFF_SHIELD", "T7_OFF_SHIELD", "T8_OFF_SHIELD",
      "T4_OFF_TOWERSHIELD_UNDEAD", "T5_OFF_TOWERSHIELD_UNDEAD", "T6_OFF_TOWERSHIELD_UNDEAD", "T7_OFF_TOWERSHIELD_UNDEAD", "T8_OFF_TOWERSHIELD_UNDEAD",
      "T4_OFF_SPIKEDSHIELD_MORGANA", "T5_OFF_SPIKEDSHIELD_MORGANA", "T6_OFF_SPIKEDSHIELD_MORGANA"
    ]
  },

  // ─── MAGE WEAPONS ───
  "Mage Weapons": {
    "Fire Staffs": [
      "T4_MAIN_FIRESTAFF", "T5_MAIN_FIRESTAFF", "T6_MAIN_FIRESTAFF", "T7_MAIN_FIRESTAFF", "T8_MAIN_FIRESTAFF",
      "T4_2H_FIRESTAFF", "T5_2H_FIRESTAFF", "T6_2H_FIRESTAFF", "T7_2H_FIRESTAFF", "T8_2H_FIRESTAFF",
      "T4_2H_INFERNOSTAFF", "T5_2H_INFERNOSTAFF", "T6_2H_INFERNOSTAFF", "T7_2H_INFERNOSTAFF", "T8_2H_INFERNOSTAFF",
      "T4_MAIN_FIRESTAFF_KEEPER", "T5_MAIN_FIRESTAFF_KEEPER", "T6_MAIN_FIRESTAFF_KEEPER", "T7_MAIN_FIRESTAFF_KEEPER", "T8_MAIN_FIRESTAFF_KEEPER",
      "T4_2H_FIRESTAFF_HELL", "T5_2H_FIRESTAFF_HELL", "T6_2H_FIRESTAFF_HELL", "T7_2H_FIRESTAFF_HELL", "T8_2H_FIRESTAFF_HELL"
    ],
    "Frost Staffs": [
      "T4_MAIN_FROSTSTAFF", "T5_MAIN_FROSTSTAFF", "T6_MAIN_FROSTSTAFF", "T7_MAIN_FROSTSTAFF", "T8_MAIN_FROSTSTAFF",
      "T4_2H_FROSTSTAFF", "T5_2H_FROSTSTAFF", "T6_2H_FROSTSTAFF", "T7_2H_FROSTSTAFF", "T8_2H_FROSTSTAFF",
      "T4_2H_GLACIALSTAFF", "T5_2H_GLACIALSTAFF", "T6_2H_GLACIALSTAFF", "T7_2H_GLACIALSTAFF", "T8_2H_GLACIALSTAFF",
      "T4_MAIN_FROSTSTAFF_KEEPER", "T5_MAIN_FROSTSTAFF_KEEPER", "T6_MAIN_FROSTSTAFF_KEEPER", "T7_MAIN_FROSTSTAFF_KEEPER", "T8_MAIN_FROSTSTAFF_KEEPER",
      "T4_2H_ICEGAUNTLETS_HELL", "T5_2H_ICEGAUNTLETS_HELL", "T6_2H_ICEGAUNTLETS_HELL", "T7_2H_ICEGAUNTLETS_HELL", "T8_2H_ICEGAUNTLETS_HELL"
    ],
    "Arcane Staffs": [
      "T4_MAIN_ARCANESTAFF", "T5_MAIN_ARCANESTAFF", "T6_MAIN_ARCANESTAFF", "T7_MAIN_ARCANESTAFF", "T8_MAIN_ARCANESTAFF",
      "T4_2H_ARCANESTAFF", "T5_2H_ARCANESTAFF", "T6_2H_ARCANESTAFF", "T7_2H_ARCANESTAFF", "T8_2H_ARCANESTAFF",
      "T4_2H_ENIGMATICSTAFF", "T5_2H_ENIGMATICSTAFF", "T6_2H_ENIGMATICSTAFF", "T7_2H_ENIGMATICSTAFF", "T8_2H_ENIGMATICSTAFF",
      "T4_MAIN_ARCANESTAFF_UNDEAD", "T5_MAIN_ARCANESTAFF_UNDEAD", "T6_MAIN_ARCANESTAFF_UNDEAD", "T7_MAIN_ARCANESTAFF_UNDEAD", "T8_MAIN_ARCANESTAFF_UNDEAD"
    ],
    "Holy Staffs": [
      "T4_MAIN_HOLYSTAFF", "T5_MAIN_HOLYSTAFF", "T6_MAIN_HOLYSTAFF", "T7_MAIN_HOLYSTAFF", "T8_MAIN_HOLYSTAFF",
      "T4_2H_HOLYSTAFF", "T5_2H_HOLYSTAFF", "T6_2H_HOLYSTAFF", "T7_2H_HOLYSTAFF", "T8_2H_HOLYSTAFF",
      "T4_2H_DIVINESTAFF", "T5_2H_DIVINESTAFF", "T6_2H_DIVINESTAFF", "T7_2H_DIVINESTAFF", "T8_2H_DIVINESTAFF",
      "T4_MAIN_HOLYSTAFF_MORGANA", "T5_MAIN_HOLYSTAFF_MORGANA", "T6_MAIN_HOLYSTAFF_MORGANA", "T7_MAIN_HOLYSTAFF_MORGANA", "T8_MAIN_HOLYSTAFF_MORGANA",
      "T4_2H_HOLYSTAFF_HELL", "T5_2H_HOLYSTAFF_HELL", "T6_2H_HOLYSTAFF_HELL", "T7_2H_HOLYSTAFF_HELL", "T8_2H_HOLYSTAFF_HELL",
      "T4_2H_HOLYSTAFF_UNDEAD", "T5_2H_HOLYSTAFF_UNDEAD", "T6_2H_HOLYSTAFF_UNDEAD", "T7_2H_HOLYSTAFF_UNDEAD", "T8_2H_HOLYSTAFF_UNDEAD"
    ],
    "Cursed Staffs": [
      "T4_MAIN_CURSEDSTAFF", "T5_MAIN_CURSEDSTAFF", "T6_MAIN_CURSEDSTAFF", "T7_MAIN_CURSEDSTAFF", "T8_MAIN_CURSEDSTAFF",
      "T4_2H_CURSEDSTAFF", "T5_2H_CURSEDSTAFF", "T6_2H_CURSEDSTAFF", "T7_2H_CURSEDSTAFF", "T8_2H_CURSEDSTAFF",
      "T4_2H_DEMONICSTAFF", "T5_2H_DEMONICSTAFF", "T6_2H_DEMONICSTAFF", "T7_2H_DEMONICSTAFF", "T8_2H_DEMONICSTAFF",
      "T4_MAIN_CURSEDSTAFF_UNDEAD", "T5_MAIN_CURSEDSTAFF_UNDEAD", "T6_MAIN_CURSEDSTAFF_UNDEAD", "T7_MAIN_CURSEDSTAFF_UNDEAD", "T8_MAIN_CURSEDSTAFF_UNDEAD",
      "T4_2H_SKULLORB_HELL", "T5_2H_SKULLORB_HELL", "T6_2H_SKULLORB_HELL", "T7_2H_SKULLORB_HELL", "T8_2H_SKULLORB_HELL"
    ],
    "Nature Staffs": [
      "T4_MAIN_NATURESTAFF", "T5_MAIN_NATURESTAFF", "T6_MAIN_NATURESTAFF", "T7_MAIN_NATURESTAFF", "T8_MAIN_NATURESTAFF",
      "T4_2H_NATURESTAFF", "T5_2H_NATURESTAFF", "T6_2H_NATURESTAFF", "T7_2H_NATURESTAFF", "T8_2H_NATURESTAFF",
      "T4_2H_WILDSTAFF", "T5_2H_WILDSTAFF", "T6_2H_WILDSTAFF", "T7_2H_WILDSTAFF", "T8_2H_WILDSTAFF",
      "T4_MAIN_NATURESTAFF_KEEPER", "T5_MAIN_NATURESTAFF_KEEPER", "T6_MAIN_NATURESTAFF_KEEPER", "T7_MAIN_NATURESTAFF_KEEPER", "T8_MAIN_NATURESTAFF_KEEPER"
    ]
  },

  // ─── HUNTER WEAPONS ───
  "Hunter Weapons": {
    "Bows": [
      "T4_2H_BOW", "T5_2H_BOW", "T6_2H_BOW", "T7_2H_BOW", "T8_2H_BOW",
      "T4_2H_WARBOW", "T5_2H_WARBOW", "T6_2H_WARBOW", "T7_2H_WARBOW", "T8_2H_WARBOW",
      "T4_2H_LONGBOW", "T5_2H_LONGBOW", "T6_2H_LONGBOW", "T7_2H_LONGBOW", "T8_2H_LONGBOW",
      "T4_2H_LONGBOW_UNDEAD", "T5_2H_LONGBOW_UNDEAD", "T6_2H_LONGBOW_UNDEAD", "T7_2H_LONGBOW_UNDEAD", "T8_2H_LONGBOW_UNDEAD",
      "T4_2H_BOW_HELL", "T5_2H_BOW_HELL", "T6_2H_BOW_HELL", "T7_2H_BOW_HELL", "T8_2H_BOW_HELL",
      "T4_2H_BOW_KEEPER", "T5_2H_BOW_KEEPER", "T6_2H_BOW_KEEPER", "T7_2H_BOW_KEEPER", "T8_2H_BOW_KEEPER"
    ],
    "Spears": [
      "T4_MAIN_SPEAR", "T5_MAIN_SPEAR", "T6_MAIN_SPEAR", "T7_MAIN_SPEAR", "T8_MAIN_SPEAR",
      "T4_2H_SPEAR", "T5_2H_SPEAR", "T6_2H_SPEAR", "T7_2H_SPEAR", "T8_2H_SPEAR",
      "T4_2H_GLAIVE", "T5_2H_GLAIVE", "T6_2H_GLAIVE", "T7_2H_GLAIVE", "T8_2H_GLAIVE",
      "T4_MAIN_SPEAR_KEEPER", "T5_MAIN_SPEAR_KEEPER", "T6_MAIN_SPEAR_KEEPER", "T7_MAIN_SPEAR_KEEPER", "T8_MAIN_SPEAR_KEEPER",
      "T4_2H_HARPOON_HELL", "T5_2H_HARPOON_HELL", "T6_2H_HARPOON_HELL", "T7_2H_HARPOON_HELL", "T8_2H_HARPOON_HELL"
    ],
    "Daggers": [
      "T4_MAIN_DAGGER", "T5_MAIN_DAGGER", "T6_MAIN_DAGGER", "T7_MAIN_DAGGER", "T8_MAIN_DAGGER",
      "T4_2H_DAGGERPAIR", "T5_2H_DAGGERPAIR", "T6_2H_DAGGERPAIR", "T7_2H_DAGGERPAIR", "T8_2H_DAGGERPAIR",
      "T4_2H_CLAWPAIR", "T5_2H_CLAWPAIR", "T6_2H_CLAWPAIR", "T7_2H_CLAWPAIR", "T8_2H_CLAWPAIR",
      "T4_MAIN_RAPIER_MORGANA", "T5_MAIN_RAPIER_MORGANA", "T6_MAIN_RAPIER_MORGANA", "T7_MAIN_RAPIER_MORGANA", "T8_MAIN_RAPIER_MORGANA"
    ],
    "Quarterstaffs": [
      "T4_2H_QUARTERSTAFF", "T5_2H_QUARTERSTAFF", "T6_2H_QUARTERSTAFF", "T7_2H_QUARTERSTAFF", "T8_2H_QUARTERSTAFF",
      "T4_2H_IRONCLADEDSTAFF", "T5_2H_IRONCLADEDSTAFF", "T6_2H_IRONCLADEDSTAFF", "T7_2H_IRONCLADEDSTAFF", "T8_2H_IRONCLADEDSTAFF",
      "T4_2H_DOUBLEBLADEDSTAFF", "T5_2H_DOUBLEBLADEDSTAFF", "T6_2H_DOUBLEBLADEDSTAFF", "T7_2H_DOUBLEBLADEDSTAFF", "T8_2H_DOUBLEBLADEDSTAFF",
      "T4_2H_TWINSCYTHE_HELL", "T5_2H_TWINSCYTHE_HELL", "T6_2H_TWINSCYTHE_HELL", "T7_2H_TWINSCYTHE_HELL", "T8_2H_TWINSCYTHE_HELL",
      "T4_2H_ROCKSTAFF_KEEPER", "T5_2H_ROCKSTAFF_KEEPER", "T6_2H_ROCKSTAFF_KEEPER", "T7_2H_ROCKSTAFF_KEEPER", "T8_2H_ROCKSTAFF_KEEPER"
    ]
  },

  // ─── ARMOR ───
  "Armor": {
    "Cloth Armor": [
      "T4_HEAD_CLOTH_SET1", "T5_HEAD_CLOTH_SET1", "T6_HEAD_CLOTH_SET1", "T7_HEAD_CLOTH_SET1", "T8_HEAD_CLOTH_SET1",
      "T4_ARMOR_CLOTH_SET1", "T5_ARMOR_CLOTH_SET1", "T6_ARMOR_CLOTH_SET1", "T7_ARMOR_CLOTH_SET1", "T8_ARMOR_CLOTH_SET1",
      "T4_SHOES_CLOTH_SET1", "T5_SHOES_CLOTH_SET1", "T6_SHOES_CLOTH_SET1", "T7_SHOES_CLOTH_SET1", "T8_SHOES_CLOTH_SET1",
      "T4_HEAD_CLOTH_SET2", "T5_HEAD_CLOTH_SET2", "T6_HEAD_CLOTH_SET2", "T7_HEAD_CLOTH_SET2", "T8_HEAD_CLOTH_SET2",
      "T4_ARMOR_CLOTH_SET2", "T5_ARMOR_CLOTH_SET2", "T6_ARMOR_CLOTH_SET2", "T7_ARMOR_CLOTH_SET2", "T8_ARMOR_CLOTH_SET2",
      "T4_SHOES_CLOTH_SET2", "T5_SHOES_CLOTH_SET2", "T6_SHOES_CLOTH_SET2", "T7_SHOES_CLOTH_SET2", "T8_SHOES_CLOTH_SET2",
      "T4_HEAD_CLOTH_SET3", "T5_HEAD_CLOTH_SET3", "T6_HEAD_CLOTH_SET3", "T7_HEAD_CLOTH_SET3", "T8_HEAD_CLOTH_SET3",
      "T4_ARMOR_CLOTH_SET3", "T5_ARMOR_CLOTH_SET3", "T6_ARMOR_CLOTH_SET3", "T7_ARMOR_CLOTH_SET3", "T8_ARMOR_CLOTH_SET3",
      "T4_SHOES_CLOTH_SET3", "T5_SHOES_CLOTH_SET3", "T6_SHOES_CLOTH_SET3", "T7_SHOES_CLOTH_SET3", "T8_SHOES_CLOTH_SET3"
    ],
    "Leather Armor": [
      "T4_HEAD_LEATHER_SET1", "T5_HEAD_LEATHER_SET1", "T6_HEAD_LEATHER_SET1", "T7_HEAD_LEATHER_SET1", "T8_HEAD_LEATHER_SET1",
      "T4_ARMOR_LEATHER_SET1", "T5_ARMOR_LEATHER_SET1", "T6_ARMOR_LEATHER_SET1", "T7_ARMOR_LEATHER_SET1", "T8_ARMOR_LEATHER_SET1",
      "T4_SHOES_LEATHER_SET1", "T5_SHOES_LEATHER_SET1", "T6_SHOES_LEATHER_SET1", "T7_SHOES_LEATHER_SET1", "T8_SHOES_LEATHER_SET1",
      "T4_HEAD_LEATHER_SET2", "T5_HEAD_LEATHER_SET2", "T6_HEAD_LEATHER_SET2", "T7_HEAD_LEATHER_SET2", "T8_HEAD_LEATHER_SET2",
      "T4_ARMOR_LEATHER_SET2", "T5_ARMOR_LEATHER_SET2", "T6_ARMOR_LEATHER_SET2", "T7_ARMOR_LEATHER_SET2", "T8_ARMOR_LEATHER_SET2",
      "T4_SHOES_LEATHER_SET2", "T5_SHOES_LEATHER_SET2", "T6_SHOES_LEATHER_SET2", "T7_SHOES_LEATHER_SET2", "T8_SHOES_LEATHER_SET2",
      "T4_HEAD_LEATHER_SET3", "T5_HEAD_LEATHER_SET3", "T6_HEAD_LEATHER_SET3", "T7_HEAD_LEATHER_SET3", "T8_HEAD_LEATHER_SET3",
      "T4_ARMOR_LEATHER_SET3", "T5_ARMOR_LEATHER_SET3", "T6_ARMOR_LEATHER_SET3", "T7_ARMOR_LEATHER_SET3", "T8_ARMOR_LEATHER_SET3",
      "T4_SHOES_LEATHER_SET3", "T5_SHOES_LEATHER_SET3", "T6_SHOES_LEATHER_SET3", "T7_SHOES_LEATHER_SET3", "T8_SHOES_LEATHER_SET3"
    ],
    "Plate Armor": [
      "T4_HEAD_PLATE_SET1", "T5_HEAD_PLATE_SET1", "T6_HEAD_PLATE_SET1", "T7_HEAD_PLATE_SET1", "T8_HEAD_PLATE_SET1",
      "T4_ARMOR_PLATE_SET1", "T5_ARMOR_PLATE_SET1", "T6_ARMOR_PLATE_SET1", "T7_ARMOR_PLATE_SET1", "T8_ARMOR_PLATE_SET1",
      "T4_SHOES_PLATE_SET1", "T5_SHOES_PLATE_SET1", "T6_SHOES_PLATE_SET1", "T7_SHOES_PLATE_SET1", "T8_SHOES_PLATE_SET1",
      "T4_HEAD_PLATE_SET2", "T5_HEAD_PLATE_SET2", "T6_HEAD_PLATE_SET2", "T7_HEAD_PLATE_SET2", "T8_HEAD_PLATE_SET2",
      "T4_ARMOR_PLATE_SET2", "T5_ARMOR_PLATE_SET2", "T6_ARMOR_PLATE_SET2", "T7_ARMOR_PLATE_SET2", "T8_ARMOR_PLATE_SET2",
      "T4_SHOES_PLATE_SET2", "T5_SHOES_PLATE_SET2", "T6_SHOES_PLATE_SET2", "T7_SHOES_PLATE_SET2", "T8_SHOES_PLATE_SET2",
      "T4_HEAD_PLATE_SET3", "T5_HEAD_PLATE_SET3", "T6_HEAD_PLATE_SET3", "T7_HEAD_PLATE_SET3", "T8_HEAD_PLATE_SET3",
      "T4_ARMOR_PLATE_SET3", "T5_ARMOR_PLATE_SET3", "T6_ARMOR_PLATE_SET3", "T7_ARMOR_PLATE_SET3", "T8_ARMOR_PLATE_SET3",
      "T4_SHOES_PLATE_SET3", "T5_SHOES_PLATE_SET3", "T6_SHOES_PLATE_SET3", "T7_SHOES_PLATE_SET3", "T8_SHOES_PLATE_SET3"
    ]
  },

  // ─── GATHERING GEAR ───
  "Gathering Gear": {
    "Tools": [
      "T4_MAIN_TOOL_SIEGEHAMMER", "T5_MAIN_TOOL_SIEGEHAMMER", "T6_MAIN_TOOL_SIEGEHAMMER", "T7_MAIN_TOOL_SIEGEHAMMER", "T8_MAIN_TOOL_SIEGEHAMMER"
    ],
    "Skinning Gear": [
      "T4_HEAD_SKINNER_SET1", "T5_HEAD_SKINNER_SET1", "T6_HEAD_SKINNER_SET1", "T7_HEAD_SKINNER_SET1", "T8_HEAD_SKINNER_SET1",
      "T4_ARMOR_SKINNER_SET1", "T5_ARMOR_SKINNER_SET1", "T6_ARMOR_SKINNER_SET1", "T7_ARMOR_SKINNER_SET1", "T8_ARMOR_SKINNER_SET1",
      "T4_SHOES_SKINNER_SET1", "T5_SHOES_SKINNER_SET1", "T6_SHOES_SKINNER_SET1", "T7_SHOES_SKINNER_SET1", "T8_SHOES_SKINNER_SET1"
    ],
    "Mining Gear": [
      "T4_HEAD_MINER_SET1", "T5_HEAD_MINER_SET1", "T6_HEAD_MINER_SET1", "T7_HEAD_MINER_SET1", "T8_HEAD_MINER_SET1",
      "T4_ARMOR_MINER_SET1", "T5_ARMOR_MINER_SET1", "T6_ARMOR_MINER_SET1", "T7_ARMOR_MINER_SET1", "T8_ARMOR_MINER_SET1",
      "T4_SHOES_MINER_SET1", "T5_SHOES_MINER_SET1", "T6_SHOES_MINER_SET1", "T7_SHOES_MINER_SET1", "T8_SHOES_MINER_SET1"
    ],
    "Harvesting Gear": [
      "T4_HEAD_HARVESTER_SET1", "T5_HEAD_HARVESTER_SET1", "T6_HEAD_HARVESTER_SET1", "T7_HEAD_HARVESTER_SET1", "T8_HEAD_HARVESTER_SET1",
      "T4_ARMOR_HARVESTER_SET1", "T5_ARMOR_HARVESTER_SET1", "T6_ARMOR_HARVESTER_SET1", "T7_ARMOR_HARVESTER_SET1", "T8_ARMOR_HARVESTER_SET1",
      "T4_SHOES_HARVESTER_SET1", "T5_SHOES_HARVESTER_SET1", "T6_SHOES_HARVESTER_SET1", "T7_SHOES_HARVESTER_SET1", "T8_SHOES_HARVESTER_SET1"
    ],
    "Lumberjack Gear": [
      "T4_HEAD_LUMBERJACK_SET1", "T5_HEAD_LUMBERJACK_SET1", "T6_HEAD_LUMBERJACK_SET1", "T7_HEAD_LUMBERJACK_SET1", "T8_HEAD_LUMBERJACK_SET1",
      "T4_ARMOR_LUMBERJACK_SET1", "T5_ARMOR_LUMBERJACK_SET1", "T6_ARMOR_LUMBERJACK_SET1", "T7_ARMOR_LUMBERJACK_SET1", "T8_ARMOR_LUMBERJACK_SET1",
      "T4_SHOES_LUMBERJACK_SET1", "T5_SHOES_LUMBERJACK_SET1", "T6_SHOES_LUMBERJACK_SET1", "T7_SHOES_LUMBERJACK_SET1", "T8_SHOES_LUMBERJACK_SET1"
    ],
    "Quarrier Gear": [
      "T4_HEAD_QUARRIER_SET1", "T5_HEAD_QUARRIER_SET1", "T6_HEAD_QUARRIER_SET1", "T7_HEAD_QUARRIER_SET1", "T8_HEAD_QUARRIER_SET1",
      "T4_ARMOR_QUARRIER_SET1", "T5_ARMOR_QUARRIER_SET1", "T6_ARMOR_QUARRIER_SET1", "T7_ARMOR_QUARRIER_SET1", "T8_ARMOR_QUARRIER_SET1",
      "T4_SHOES_QUARRIER_SET1", "T5_SHOES_QUARRIER_SET1", "T6_SHOES_QUARRIER_SET1", "T7_SHOES_QUARRIER_SET1", "T8_SHOES_QUARRIER_SET1"
    ]
  },

  // ─── ACCESSORIES ───
  "Accessories": {
    "Off-Hand": [
      "T4_OFF_BOOK", "T5_OFF_BOOK", "T6_OFF_BOOK", "T7_OFF_BOOK", "T8_OFF_BOOK",
      "T4_OFF_TORCH", "T5_OFF_TORCH", "T6_OFF_TORCH", "T7_OFF_TORCH", "T8_OFF_TORCH",
      "T4_OFF_HORN_KEEPER", "T5_OFF_HORN_KEEPER", "T6_OFF_HORN_KEEPER", "T7_OFF_HORN_KEEPER", "T8_OFF_HORN_KEEPER",
      "T4_OFF_JESTERCANE_HELL", "T5_OFF_JESTERCANE_HELL", "T6_OFF_JESTERCANE_HELL", "T7_OFF_JESTERCANE_HELL", "T8_OFF_JESTERCANE_HELL",
      "T4_OFF_LAMP_UNDEAD", "T5_OFF_LAMP_UNDEAD", "T6_OFF_LAMP_UNDEAD", "T7_OFF_LAMP_UNDEAD", "T8_OFF_LAMP_UNDEAD",
      "T4_OFF_ORB_MORGANA", "T5_OFF_ORB_MORGANA", "T6_OFF_ORB_MORGANA", "T7_OFF_ORB_MORGANA", "T8_OFF_ORB_MORGANA"
    ]
  },

  // ─── ENCHANTING MATERIALS ───
  "Enchanting Materials": {
    "Runes": [
      "T4_RUNE", "T5_RUNE", "T6_RUNE", "T7_RUNE", "T8_RUNE"
    ],
    "Souls": [
      "T4_SOUL", "T5_SOUL", "T6_SOUL", "T7_SOUL", "T8_SOUL"
    ],
    "Relics": [
      "T4_RELIC", "T5_RELIC", "T6_RELIC", "T7_RELIC", "T8_RELIC"
    ]
  }
};

// Human-readable item names derived from IDs
function formatItemName(itemId) {
  // Handle enchantment levels
  let enchant = 0;
  let baseId = itemId;
  if (itemId.includes('@')) {
    const parts = itemId.split('@');
    baseId = parts[0];
    enchant = parseInt(parts[1]);
  }

  const tier = baseId.match(/^T(\d)/)?.[1] || '';

  // Remove tier prefix
  let name = baseId.replace(/^T\d_/, '');

  // Mapping of common internal names to human-readable names
  const nameMap = {
    'HIDE': 'Hide', 'ORE': 'Ore', 'FIBER': 'Fiber', 'WOOD': 'Wood', 'ROCK': 'Rock',
    'LEATHER': 'Leather', 'METALBAR': 'Metal Bar', 'CLOTH': 'Cloth', 'PLANKS': 'Planks', 'STONEBLOCK': 'Stoneblock',
    'BAG': 'Bag', 'MOUNT_HORSE': 'Riding Horse', 'MOUNT_ARMORED_HORSE': 'Armored Horse', 'MOUNT_OX': 'Ox',
    'MAIN_SWORD': 'Broadsword', '2H_CLAYMORE': 'Claymore', '2H_DUALSWORD': 'Dual Swords',
    'MAIN_SCIMITAR_MORGANA': 'Clarent Blade', '2H_CLEAVER_HELL': 'Carving Sword', '2H_DUALSCIMITAR_UNDEAD': 'Galatine Pair',
    'MAIN_AXE': 'Battleaxe', '2H_HALBERD': 'Halberd', '2H_HALBERD_MORGANA': 'Bear Paws',
    '2H_DUALAXE': 'Greataxe',
    'MAIN_MACE': 'Mace', '2H_MACE': 'Heavy Mace', '2H_FLAIL': 'Morning Star',
    'MAIN_ROCKMACE_KEEPER': 'Bedrock Mace',
    '2H_POLEHAMMER': 'Polehammer', '2H_HAMMER': 'Great Hammer',
    '2H_HAMMER_UNDEAD': 'Tombhammer', '2H_DUALHAMMER_HELL': 'Forge Hammers',
    '2H_CROSSBOW': 'Crossbow', '2H_CROSSBOWLARGE': 'Heavy Crossbow', 'MAIN_1HCROSSBOW': 'Light Crossbow',
    'OFF_SHIELD': 'Shield', 'OFF_TOWERSHIELD_UNDEAD': 'Sarcophagus', 'OFF_SPIKEDSHIELD_MORGANA': 'Caitiff Shield',
    'MAIN_FIRESTAFF': 'Fire Staff', '2H_FIRESTAFF': 'Great Fire Staff', '2H_INFERNOSTAFF': 'Infernal Staff',
    'MAIN_FIRESTAFF_KEEPER': 'Wildfire Staff', '2H_FIRESTAFF_HELL': 'Brimstone Staff',
    'MAIN_FROSTSTAFF': 'Frost Staff', '2H_FROSTSTAFF': 'Great Frost Staff', '2H_GLACIALSTAFF': 'Glacial Staff',
    'MAIN_FROSTSTAFF_KEEPER': 'Hoarfrost Staff', '2H_ICEGAUNTLETS_HELL': 'Icicle Staff',
    'MAIN_ARCANESTAFF': 'Arcane Staff', '2H_ARCANESTAFF': 'Great Arcane Staff', '2H_ENIGMATICSTAFF': 'Enigmatic Staff',
    'MAIN_ARCANESTAFF_UNDEAD': 'Witchwork Staff',
    'MAIN_HOLYSTAFF': 'Holy Staff', '2H_HOLYSTAFF': 'Great Holy Staff', '2H_DIVINESTAFF': 'Divine Staff',
    'MAIN_HOLYSTAFF_MORGANA': 'Lifetouch Staff', '2H_HOLYSTAFF_HELL': 'Fallen Staff', '2H_HOLYSTAFF_UNDEAD': 'Redemption Staff',
    'MAIN_CURSEDSTAFF': 'Cursed Staff', '2H_CURSEDSTAFF': 'Great Cursed Staff', '2H_DEMONICSTAFF': 'Demonic Staff',
    'MAIN_CURSEDSTAFF_UNDEAD': 'Lifecurse Staff', '2H_SKULLORB_HELL': 'Cursed Skull',
    'MAIN_NATURESTAFF': 'Nature Staff', '2H_NATURESTAFF': 'Great Nature Staff', '2H_WILDSTAFF': 'Wild Staff',
    'MAIN_NATURESTAFF_KEEPER': 'Druidic Staff',
    '2H_BOW': 'Bow', '2H_WARBOW': 'Warbow', '2H_LONGBOW': 'Longbow',
    '2H_LONGBOW_UNDEAD': 'Whispering Bow', '2H_BOW_HELL': 'Wailing Bow', '2H_BOW_KEEPER': 'Badon Bow',
    'MAIN_SPEAR': 'Spear', '2H_SPEAR': 'Pike', '2H_GLAIVE': 'Glaive',
    'MAIN_SPEAR_KEEPER': 'Trinity Spear', '2H_HARPOON_HELL': 'Heron Spear',
    'MAIN_DAGGER': 'Dagger', '2H_DAGGERPAIR': 'Dagger Pair', '2H_CLAWPAIR': 'Claws',
    'MAIN_RAPIER_MORGANA': 'Bloodletter',
    '2H_QUARTERSTAFF': 'Quarterstaff', '2H_IRONCLADEDSTAFF': 'Iron-clad Staff', '2H_DOUBLEBLADEDSTAFF': 'Double-bladed Staff',
    '2H_TWINSCYTHE_HELL': 'Black Monk Stave', '2H_ROCKSTAFF_KEEPER': 'Staff of Balance',
    'HEAD_CLOTH_SET1': 'Scholar Cowl', 'ARMOR_CLOTH_SET1': 'Scholar Robe', 'SHOES_CLOTH_SET1': 'Scholar Sandals',
    'HEAD_CLOTH_SET2': 'Cleric Cowl', 'ARMOR_CLOTH_SET2': 'Cleric Robe', 'SHOES_CLOTH_SET2': 'Cleric Sandals',
    'HEAD_CLOTH_SET3': 'Mage Cowl', 'ARMOR_CLOTH_SET3': 'Mage Robe', 'SHOES_CLOTH_SET3': 'Mage Sandals',
    'HEAD_LEATHER_SET1': 'Mercenary Hood', 'ARMOR_LEATHER_SET1': 'Mercenary Jacket', 'SHOES_LEATHER_SET1': 'Mercenary Shoes',
    'HEAD_LEATHER_SET2': 'Hunter Hood', 'ARMOR_LEATHER_SET2': 'Hunter Jacket', 'SHOES_LEATHER_SET2': 'Hunter Shoes',
    'HEAD_LEATHER_SET3': 'Assassin Hood', 'ARMOR_LEATHER_SET3': 'Assassin Jacket', 'SHOES_LEATHER_SET3': 'Assassin Shoes',
    'HEAD_PLATE_SET1': 'Soldier Helmet', 'ARMOR_PLATE_SET1': 'Soldier Armor', 'SHOES_PLATE_SET1': 'Soldier Boots',
    'HEAD_PLATE_SET2': 'Knight Helmet', 'ARMOR_PLATE_SET2': 'Knight Armor', 'SHOES_PLATE_SET2': 'Knight Boots',
    'HEAD_PLATE_SET3': 'Guardian Helmet', 'ARMOR_PLATE_SET3': 'Guardian Armor', 'SHOES_PLATE_SET3': 'Guardian Boots',
    'MAIN_TOOL_SIEGEHAMMER': 'Demolition Hammer',
    'HEAD_SKINNER_SET1': 'Skinner Cap', 'ARMOR_SKINNER_SET1': 'Skinner Garb', 'SHOES_SKINNER_SET1': 'Skinner Workboots',
    'HEAD_MINER_SET1': 'Miner Cap', 'ARMOR_MINER_SET1': 'Miner Garb', 'SHOES_MINER_SET1': 'Miner Workboots',
    'HEAD_HARVESTER_SET1': 'Harvester Cap', 'ARMOR_HARVESTER_SET1': 'Harvester Garb', 'SHOES_HARVESTER_SET1': 'Harvester Workboots',
    'HEAD_LUMBERJACK_SET1': 'Lumberjack Cap', 'ARMOR_LUMBERJACK_SET1': 'Lumberjack Garb', 'SHOES_LUMBERJACK_SET1': 'Lumberjack Workboots',
    'HEAD_QUARRIER_SET1': 'Quarrier Cap', 'ARMOR_QUARRIER_SET1': 'Quarrier Garb', 'SHOES_QUARRIER_SET1': 'Quarrier Workboots',
    'OFF_BOOK': 'Tome of Spells', 'OFF_TORCH': 'Torch', 'OFF_HORN_KEEPER': 'Mistcaller',
    'OFF_JESTERCANE_HELL': 'Leering Cane', 'OFF_LAMP_UNDEAD': 'Cryptcandle', 'OFF_ORB_MORGANA': 'Eye of Secrets',
    'POTION_HEAL': 'Healing Potion', 'POTION_ENERGY': 'Energy Potion', 'POTION_COOLDOWN': 'Gigantify Potion',
    'POTION_RESISTANCE': 'Resistance Potion', 'POTION_MOB_TRACKING': 'Invisibility Potion',
    'MEAL_SOUP': 'Soup', 'MEAL_SALAD': 'Salad', 'MEAL_SANDWICH': 'Sandwich',
    'MEAL_PIE': 'Pie', 'MEAL_OMELETTE': 'Omelette', 'MEAL_STEW': 'Stew',
    'CARROT': 'Carrot', 'BEAN': 'Bean', 'WHEAT': 'Wheat', 'TURNIP': 'Turnip',
    'CABBAGE': 'Cabbage', 'POTATO': 'Potato', 'CORN': 'Corn', 'PUMPKIN': 'Pumpkin',
    'FISHSAUCE': 'Fish Sauce',
    'CAPEITEM_FW_BRIDGEWATCH': 'Bridgewatch Cape', 'CAPEITEM_FW_FORTSTERLING': 'Fort Sterling Cape',
    'CAPEITEM_FW_LYMHURST': 'Lymhurst Cape', 'CAPEITEM_FW_MARTLOCK': 'Martlock Cape',
    'CAPEITEM_FW_THETFORD': 'Thetford Cape', 'CAPEITEM_FW_CAERLEON': 'Caerleon Cape',
    'RUNE': 'Rune', 'SOUL': 'Soul', 'RELIC': 'Relic'
  };

  const readableName = nameMap[name] || name.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const enchantStr = enchant > 0 ? `.${enchant}` : '';
  return `T${tier}${enchantStr} ${readableName}`;
}

// Get tier from item ID
function getItemTier(itemId) {
  const match = itemId.match(/^T(\d)/);
  return match ? parseInt(match[1]) : 0;
}

// Get enchantment from item ID
function getItemEnchantment(itemId) {
  if (itemId.includes('@')) {
    return parseInt(itemId.split('@')[1]);
  }
  return 0;
}

// Get all item IDs from selected categories
function getItemsByCategories(categories) {
  const items = [];
  for (const category of categories) {
    if (ITEM_DATABASE[category]) {
      for (const subcategory of Object.values(ITEM_DATABASE[category])) {
        items.push(...subcategory);
      }
    }
  }
  return items;
}

// Get all item IDs
function getAllItems() {
  return getItemsByCategories(Object.keys(ITEM_DATABASE));
}

// Get flat list of categories
function getCategoryNames() {
  return Object.keys(ITEM_DATABASE);
}

// Get subcategories
function getSubcategories(category) {
  return Object.keys(ITEM_DATABASE[category] || {});
}

// Categories that contain enchantable equipment
const ENCHANTABLE_CATEGORIES = [
  'Warrior Weapons', 'Mage Weapons', 'Hunter Weapons',
  'Armor', 'Gathering Gear', 'Accessories', 'Bags & Capes'
];

// Get base item ID (strip enchantment)
function getBaseItemId(itemId) {
  return itemId.split('@')[0];
}

// Get enchanting material ID for a tier and upgrade level
function getEnchantMaterialId(tier, level) {
  // level 1 = rune, level 2 = soul, level 3 = relic
  const types = { 1: 'RUNE', 2: 'SOUL', 3: 'RELIC' };
  return `T${tier}_${types[level]}`;
}

// Get enchanting material count based on item slot
// 96: head, boots, off-hand, capes  |  192: chest, bags  |  288: 1H weapons  |  384: 2H weapons
function getEnchantMatCount(itemId) {
  const base = getBaseItemId(itemId);
  const stripped = base.replace(/^T\d_/, ''); // remove tier prefix
  if (stripped.startsWith('2H_')) return 384;
  if (stripped.startsWith('MAIN_') || stripped.startsWith('MH_')) return 288;
  if (stripped.startsWith('ARMOR_')) return 192;
  if (stripped.startsWith('BAG')) return 192;
  if (stripped.startsWith('HEAD_')) return 96;
  if (stripped.startsWith('SHOES_')) return 96;
  if (stripped.startsWith('OFF_')) return 96;
  if (stripped.startsWith('CAPEITEM')) return 96;
  return 96; // default fallback
}

// Get enchantable items from selected categories (base items only, no @N variants)
function getEnchantableItems(categories) {
  const items = [];
  for (const cat of categories) {
    if (!ENCHANTABLE_CATEGORIES.includes(cat)) continue;
    if (ITEM_DATABASE[cat]) {
      for (const subcategory of Object.values(ITEM_DATABASE[cat])) {
        for (const itemId of subcategory) {
          if (!itemId.includes('@')) {
            items.push(itemId);
          }
        }
      }
    }
  }
  return items;
}
